
export const routes = [
  {
    path:'/',
    name:'Main',
    component:()=>import('../views/Main.vue'),
    children:[
      {
        path:'movie',
        // path:'movie/:name',
        alias:'',
       name:'Movie',
    component:()=>import('../views/Movie.vue'),
      },
      {
        path:'video',
    name:'Video',
    component:()=>import('../views/Video.vue'),
      },
      {
        path:'smallvideo',
    name:'SmallVideo',
    component:()=>import('../views/SmallVideo.vue'),
      },
      {
        path:'my',
    name:'My',
    component:()=>import('../views/My.vue'),
      },
    ]
  },
  {
    path:'/city',
    name:'City',
    component:()=>import('../views/City.vue')
  },
  {
    path:'/detail/:id',
    name:'Detail',
    component:()=>import('../views/Detail.vue')
  },
  {
    path:'/intro',
    name:'Intro',
    component:()=>import('../views/Intro.vue')
  },
  {
    path:'/playVideo',
    name:'PlayVideo',
    component:()=>import('../views/PlayVideo.vue')
  },
  {
    path:'/playSmallVideo',
    name:'PlaySmallVideo',
    component:()=>import('../views/PlaySmallVideo.vue')
  },
  {
    path:'/search',
    name:'Search',
    component:()=>import('../views/Search.vue')
  },
  {
    path:'/allMovies',
    name:'AllMovies',
    component:()=>import('../views/AllMovies.vue')
  },
  {
    path:'/searchCinema',
    name:'SearchCinema',
    component:()=>import('../views/SearchCinema.vue')
  },
  {
    path:'/cinemaDetail',
    name:'CinemaDetail',
    component:()=>import('../views/CinemaDetail.vue')
  },
  {
    path:'/login',
    name:'Login',
    component:()=>import('../views/Login.vue')
  },
  {
    path:'/playDetailVideo',
    name:'PlayDetailVideo',
    component:()=>import('../views/PlayDetailVideo.vue')
  },
  {
    path:'/looked',
    name:'Looked',
    component:()=>import('../views/Looked.vue')
  },
  {
    path:'/movieCinema',
    name:'MovieCinema',
    component:()=>import('../views/MovieCinema.vue')
  },
  {
    path:'/orderList',
    name:'OrderList',
    component:()=>import('../views/OrderList.vue')
  },
]
  
  